# Understat (title) -> football-data.co.uk (HomeTeam/AwayTeam), ricavata da 21.569 partite 2014-2026
UNDERSTAT_ALIASES = {
    # D1
    'Arminia Bielefeld': 'Bielefeld',
    'Augsburg': 'Augsburg',
    'Bayer Leverkusen': 'Leverkusen',
    'Bayern Munich': 'Bayern Munich',
    'Bochum': 'Bochum',
    'Borussia Dortmund': 'Dortmund',
    'Borussia M.Gladbach': "M'gladbach",  # nei CSV recenti; in alcune stagioni 'MGladbach'
    'Darmstadt': 'Darmstadt',
    'Eintracht Frankfurt': 'Ein Frankfurt',
    'Elversberg': 'Elversberg',
    'FC Cologne': 'FC Koln',
    'FC Heidenheim': 'Heidenheim',
    'Fortuna Duesseldorf': 'Fortuna Dusseldorf',
    'Freiburg': 'Freiburg',
    'Greuther Fuerth': 'Greuther Furth',
    'Hamburger SV': 'Hamburg',
    'Hannover 96': 'Hannover',
    'Hertha Berlin': 'Hertha',
    'Hoffenheim': 'Hoffenheim',
    'Holstein Kiel': 'Holstein Kiel',
    'Ingolstadt': 'Ingolstadt',
    'Mainz 05': 'Mainz',
    'Nuernberg': 'Nurnberg',
    'Paderborn': 'Paderborn',
    'RasenBallsport Leipzig': 'RB Leipzig',
    'Schalke 04': 'Schalke 04',
    'St. Pauli': 'St Pauli',
    'Union Berlin': 'Union Berlin',
    'VfB Stuttgart': 'Stuttgart',
    'Werder Bremen': 'Werder Bremen',
    'Wolfsburg': 'Wolfsburg',
    # E0
    'Arsenal': 'Arsenal',
    'Aston Villa': 'Aston Villa',
    'Bournemouth': 'Bournemouth',
    'Brentford': 'Brentford',
    'Brighton': 'Brighton',
    'Burnley': 'Burnley',
    'Cardiff': 'Cardiff',
    'Chelsea': 'Chelsea',
    'Coventry': 'Coventry',
    'Crystal Palace': 'Crystal Palace',
    'Everton': 'Everton',
    'Fulham': 'Fulham',
    'Huddersfield': 'Huddersfield',
    'Hull': 'Hull',
    'Ipswich': 'Ipswich',
    'Leeds': 'Leeds',
    'Leicester': 'Leicester',
    'Liverpool': 'Liverpool',
    'Luton': 'Luton',
    'Manchester City': 'Man City',
    'Manchester United': 'Man United',
    'Middlesbrough': 'Middlesbrough',
    'Newcastle United': 'Newcastle',
    'Norwich': 'Norwich',
    'Nottingham Forest': "Nott'm Forest",  # nei CSV recenti; in alcune stagioni 'Nottm Forest'
    'Queens Park Rangers': 'QPR',
    'Sheffield United': 'Sheffield United',
    'Southampton': 'Southampton',
    'Stoke': 'Stoke',
    'Sunderland': 'Sunderland',
    'Swansea': 'Swansea',
    'Tottenham': 'Tottenham',
    'Watford': 'Watford',
    'West Bromwich Albion': 'West Brom',
    'West Ham': 'West Ham',
    'Wolverhampton Wanderers': 'Wolves',
    # F1
    'Ajaccio': 'Ajaccio',
    'Amiens': 'Amiens',
    'Angers': 'Angers',
    'Auxerre': 'Auxerre',
    'Bordeaux': 'Bordeaux',
    'Brest': 'Brest',
    'Caen': 'Caen',
    'Clermont Foot': 'Clermont',
    'Dijon': 'Dijon',
    'Evian Thonon Gaillard': 'Evian Thonon Gaillard',
    'GFC Ajaccio': 'Ajaccio GFCO',
    'Guingamp': 'Guingamp',
    'Le Havre': 'Le Havre',
    'Le Mans': 'Le Mans',
    'Lens': 'Lens',
    'Lille': 'Lille',
    'Lorient': 'Lorient',
    'Lyon': 'Lyon',
    'Marseille': 'Marseille',
    'Metz': 'Metz',
    'Monaco': 'Monaco',
    'Montpellier': 'Montpellier',
    'Nancy': 'Nancy',
    'Nantes': 'Nantes',
    'Nice': 'Nice',
    'Nimes': 'Nimes',
    'Paris FC': 'Paris FC',
    'Paris Saint Germain': 'Paris SG',
    'Reims': 'Reims',
    'Rennes': 'Rennes',
    'SC Bastia': 'Bastia',
    'Saint-Etienne': 'St Etienne',
    'Strasbourg': 'Strasbourg',
    'Toulouse': 'Toulouse',
    'Troyes': 'Troyes',
    # I1
    'AC Milan': 'Milan',
    'Atalanta': 'Atalanta',
    'Benevento': 'Benevento',
    'Bologna': 'Bologna',
    'Brescia': 'Brescia',
    'Cagliari': 'Cagliari',
    'Carpi': 'Carpi',
    'Cesena': 'Cesena',
    'Chievo': 'Chievo',
    'Como': 'Como',
    'Cremonese': 'Cremonese',
    'Crotone': 'Crotone',
    'Empoli': 'Empoli',
    'Fiorentina': 'Fiorentina',
    'Frosinone': 'Frosinone',
    'Genoa': 'Genoa',
    'Inter': 'Inter',
    'Juventus': 'Juventus',
    'Lazio': 'Lazio',
    'Lecce': 'Lecce',
    'Monza': 'Monza',
    'Napoli': 'Napoli',
    'Palermo': 'Palermo',
    'Parma': 'Parma',
    'Parma Calcio 1913': 'Parma',
    'Pescara': 'Pescara',
    'Pisa': 'Pisa',
    'Roma': 'Roma',
    'SPAL 2013': 'Spal',
    'Salernitana': 'Salernitana',
    'Sampdoria': 'Sampdoria',
    'Sassuolo': 'Sassuolo',
    'Spezia': 'Spezia',
    'Torino': 'Torino',
    'Udinese': 'Udinese',
    'Venezia': 'Venezia',
    'Verona': 'Verona',
    # SP1
    'Alaves': 'Alaves',
    'Almeria': 'Almeria',
    'Athletic Club': 'Ath Bilbao',
    'Atletico Madrid': 'Ath Madrid',
    'Barcelona': 'Barcelona',
    'Cadiz': 'Cadiz',
    'Celta Vigo': 'Celta',
    'Cordoba': 'Cordoba',
    'Deportivo La Coruna': 'La Coruna',
    'Eibar': 'Eibar',
    'Elche': 'Elche',
    'Espanyol': 'Espanol',
    'Getafe': 'Getafe',
    'Girona': 'Girona',
    'Granada': 'Granada',
    'Las Palmas': 'Las Palmas',
    'Leganes': 'Leganes',
    'Levante': 'Levante',
    'Malaga': 'Malaga',
    'Mallorca': 'Mallorca',
    'Osasuna': 'Osasuna',
    'Racing Santander': 'Santander',
    'Rayo Vallecano': 'Vallecano',
    'Real Betis': 'Betis',
    'Real Madrid': 'Real Madrid',
    'Real Oviedo': 'Oviedo',
    'Real Sociedad': 'Sociedad',
    'Real Valladolid': 'Valladolid',
    'SD Huesca': 'Huesca',
    'Sevilla': 'Sevilla',
    'Sporting Gijon': 'Sp Gijon',
    'Valencia': 'Valencia',
    'Villarreal': 'Villarreal',
}
